void communication_setup();

enum flight_controller_registers
{
    UNSET,

	MOVE,
	SET_DIRECTION,
    SET_HEIGHT,
    SET_BASE_ACCELERATION,

    SET_PITCH_PROP_COEF,
    SET_PITCH_DER_COEF,
    SET_PITCH_INT_COEF,

    SET_ROLL_PROP_COEF,
    SET_ROLL_DER_COEF,
    SET_ROLL_INT_COEF,

    SET_YAW_PROP_COEF,
    SET_YAW_DER_COEF,
    SET_YAW_INT_COEF,

    SET_HEIGHT_PROP_COEF,
    SET_HEIGHT_DER_COEF,
    SET_HEIGHT_INT_COEF,

    SET_ACC_TRUST,
    SET_MAG_TRUST,
    SET_ACC_FILTERING,

    SET_ACC_LPF_MODE,
    SET_GYRO_LPF_MODE,
    RESET_TURN_OFF_TRIGGER,
    SET_TURN_OFF_INCLINE_ANGLE,

    SET_PITCH_ADJUST,
    SET_ROLL_ADJUST,
    
    CALIBRATE_GYRO,
    CALIBRATE_MAG,
    CALIBRATE_ESC,

    SET_GYRO_CALIBRATION,
    SET_MAG_CALIBRATION,

    GET_PITCH_AND_ROLL_INFO,
    GET_YAW_AND_HEIGHT_INFO,
    GET_MOTOR_VALS_FREQ_AND_VOLTAGE,

    GET_GYRO_CALIBRATION,
    GET_MAG_CALIBRATION,

    RESET_LANDING_FLAG,
    GET_PRIMARY_INFO,
    SWITCH_TO_RELATIVE_ACCELERATION,
    SET_RELATIVE_ACCELERATION,

    SET_US_HEIGHT_FILTERING,
    SET_US_HEIGHT_DER_FILTERING,

    CALIBRATE_ACC,
    SET_PITCH_I_LIMIT,
    SET_ROLL_I_LIMIT,
    SET_YAW_I_LIMIT,
    SET_HEIGHT_I_LIMIT,
    GET_ACC_CALIBRATION,
    SET_ACC_CALIBRATION,

    SET_MOTOR_CURVE_A,
    SET_MOTOR_CURVE_B,
    SET_VOLTAGE_DROP_CURVE_A,
    SET_VOLTAGE_DROP_CURVE_B,
    SET_POWER_LOSS_CURVE_A,
    SET_POWER_LOSS_CURVE_B,

    SET_HEIGHT_NEGATIVE_INT_COEF,

    // SET_POSITION_PROP_COEF,
    // SET_POSITION_DER_COEF,
    // SET_POSITION_INT_COEF,
    // SET_POSITION_I_LIMIT,
    SET_BAR_HEIGHT_PROP_COEF,
    SET_BAR_HEIGHT_DER_COEF,
    SET_BAR_HEIGHT_INT_COEF,
    SET_BAR_HEIGHT_FILTERING,
    SET_BAR_HEIGHT_DER_FILTERING,
    // SET_POSITION_FILTERING,
    // SET_POSITION_DER_FILTERING,
    SET_HOLD_MODE,
    // GET_POSITION_INFO,
    MOVE_LOCAL,
    GET_HEIGHT_AND_DIRECTION
};